# Generated by Django 5.1 on 2024-11-28 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Phone', models.BigIntegerField(max_length=20)),
                ('Email', models.EmailField(max_length=255)),
            ],
        ),
    ]
